"""squashed baseline schema

Revision ID: e7f8a9b0c1d2
Revises:
Create Date: 2026-03-21 12:42:28.736873

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e7f8a9b0c1d2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_docs_is_visible"), "docs", ["is_visible"], unique=False)
    op.create_index(op.f("ix_docs_title"), "docs", ["title"], unique=False)
    op.create_table(
        "emby_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("external_url", sa.String(length=255), nullable=True),
        sa.Column("backup_url", sa.String(length=255), nullable=True),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("webhook_url", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emby_servers_name"), "emby_servers", ["name"], unique=False)
    op.create_index(op.f("ix_emby_servers_priority"), "emby_servers", ["priority"], unique=False)
    op.create_table(
        "moviepilot_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("api_token", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latency", sa.Integer(), nullable=True),
        sa.Column("last_check_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_moviepilot_servers_name"), "moviepilot_servers", ["name"], unique=False
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=False),
        sa.Column("group_name", sa.String(length=255), nullable=False),
        sa.Column("tier_level", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "default_billing_cycle",
            sa.Enum(
                "TRIAL",
                "UNSET",
                "MONTHLY",
                "QUARTERLY",
                "SEMI_ANNUAL",
                "YEARLY",
                "LIFETIME",
                name="billingcycle",
            ),
            nullable=False,
        ),
        sa.Column("trial_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("trial_days", sa.Integer(), nullable=True),
        sa.Column("monthly_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("quarterly_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("semi_annual_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("annual_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("lifetime_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("auto_renew_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "server_allocation_strategy",
            sa.Enum("ALL", "LEAST_LOAD", name="planserverallocationstrategy"),
            nullable=False,
        ),
        sa.Column("vod_times", sa.Integer(), nullable=True),
        sa.Column("vod_movie_times", sa.Integer(), nullable=False),
        sa.Column("vod_tv_times", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("status", sa.Enum("ON", "OFF", name="planstatus"), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_key", "tier_level", name="uq_plan_group_tier"),
    )
    op.create_index(op.f("ix_plans_group_key"), "plans", ["group_key"], unique=False)
    op.create_index(op.f("ix_plans_group_name"), "plans", ["group_name"], unique=False)
    op.create_index(op.f("ix_plans_name"), "plans", ["name"], unique=False)
    op.create_table(
        "subscription_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("tier_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_subscription_groups_key"),
        sa.UniqueConstraint("name", name="uq_subscription_groups_name"),
    )
    op.create_index(
        op.f("ix_subscription_groups_key"), "subscription_groups", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_groups_name"), "subscription_groups", ["name"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("default_theme", sa.String(length=16), nullable=False),
        sa.Column("email_verification_enabled", sa.Boolean(), nullable=False),
        sa.Column("smtp_host", sa.String(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column("smtp_user", sa.String(length=255), nullable=True),
        sa.Column("smtp_password", sa.String(length=255), nullable=True),
        sa.Column("smtp_from", sa.String(length=255), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=False),
        sa.Column("smtp_use_ssl", sa.Boolean(), nullable=False),
        sa.Column("epay_enabled", sa.Boolean(), nullable=False),
        sa.Column("refund_enabled", sa.Boolean(), nullable=False),
        sa.Column("refund_window_days", sa.Integer(), nullable=False),
        sa.Column("refund_forbid_if_vod_used", sa.Boolean(), nullable=False),
        sa.Column("refund_vod_used_threshold", sa.Integer(), nullable=False),
        sa.Column("refund_user_monthly_limit", sa.Integer(), nullable=False),
        sa.Column("refund_user_monthly_window_days", sa.Integer(), nullable=False),
        sa.Column("epay_merchant_id", sa.String(length=64), nullable=True),
        sa.Column("epay_key", sa.String(length=255), nullable=True),
        sa.Column("epay_gateway", sa.String(length=255), nullable=True),
        sa.Column("epay_notify_url", sa.String(length=255), nullable=True),
        sa.Column("epay_return_url", sa.String(length=255), nullable=True),
        sa.Column("site_name", sa.String(length=128), nullable=True),
        sa.Column("site_url", sa.String(length=255), nullable=True),
        sa.Column("site_logo_url", sa.String(length=255), nullable=True),
        sa.Column("task_log_retention_days", sa.Integer(), nullable=False),
        sa.Column("subscription_retention_days", sa.Integer(), nullable=False),
        sa.Column("tmdb_base_url", sa.String(length=255), nullable=True),
        sa.Column("tmdb_api_key", sa.String(length=255), nullable=True),
        sa.Column("tmdb_proxy_url", sa.String(length=255), nullable=True),
        sa.Column("tmdb_cache_search_ttl", sa.Integer(), nullable=True),
        sa.Column("tmdb_cache_discover_ttl", sa.Integer(), nullable=True),
        sa.Column("tmdb_cache_genres_ttl", sa.Integer(), nullable=True),
        sa.Column("tmdb_cache_companies_ttl", sa.Integer(), nullable=True),
        sa.Column("tmdb_warmup_enabled", sa.Boolean(), nullable=False),
        sa.Column("tmdb_warmup_categories", sa.String(length=255), nullable=True),
        sa.Column("tmdb_warmup_include_genres", sa.Boolean(), nullable=False),
        sa.Column("tmdb_warmup_include_companies", sa.Boolean(), nullable=False),
        sa.Column("tmdb_warmup_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=32), nullable=True),
        sa.Column("last_message", sa.String(length=1000), nullable=True),
        sa.Column("last_duration_ms", sa.Integer(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_tasks_key"), "system_tasks", ["key"], unique=True)
    op.create_table(
        "tmdb_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tmdb_cache_cache_key"), "tmdb_cache", ["cache_key"], unique=True)
    op.create_index(op.f("ix_tmdb_cache_expires_at"), "tmdb_cache", ["expires_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("email_verification_token", sa.String(length=128), nullable=True),
        sa.Column("email_verification_expires_at", sa.DateTime(), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("expire_remind", sa.Boolean(), nullable=False),
        sa.Column("trial_used", sa.Boolean(), nullable=False),
        sa.Column("inviter_user_id", sa.UUID(), nullable=True),
        sa.Column("vod_movie_limit", sa.Integer(), nullable=False),
        sa.Column("vod_tv_limit", sa.Integer(), nullable=False),
        sa.Column("vod_movie_used", sa.Integer(), nullable=False),
        sa.Column("vod_tv_used", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BANNED", "ABNORMAL", "DELETED", name="userstatus"),
            nullable=True,
        ),
        sa.Column("role", sa.Enum("USER", "ADMIN", "SUPERADMIN", name="userrole"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inviter_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email_verification_token"),
        "users",
        ["email_verification_token"],
        unique=False,
    )
    op.create_index(op.f("ix_users_inviter_user_id"), "users", ["inviter_user_id"], unique=False)
    op.create_index(
        "uq_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_users_username_active",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "vod_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auto_approve", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "balance_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("operator_user_id", sa.UUID(), nullable=False),
        sa.Column("delta", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("before_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("after_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operator_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_transactions_operator_user_id"),
        "balance_transactions",
        ["operator_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_transactions_user_id"), "balance_transactions", ["user_id"], unique=False
    )
    op.create_table(
        "emby_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("emby_server_id", sa.UUID(), nullable=False),
        sa.Column("emby_user_id", sa.String(length=255), nullable=False),
        sa.Column("emby_username", sa.String(length=255), nullable=False),
        sa.Column("emby_password", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["emby_server_id"],
            ["emby_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "emby_server_id", name="uq_emby_account_user_server"),
    )
    op.create_index(
        op.f("ix_emby_accounts_emby_server_id"), "emby_accounts", ["emby_server_id"], unique=False
    )
    op.create_index(op.f("ix_emby_accounts_user_id"), "emby_accounts", ["user_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("invitee_email", sa.String(length=255), nullable=False),
        sa.Column("inviter_user_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=True),
        sa.Column("initial_balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "EXPIRED", name="invitationstatus"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inviter_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_inviter_user_id"), "invitations", ["inviter_user_id"], unique=False
    )
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=True),
        sa.Column("order_no", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Enum("PLAN", "VOD", "RECHARGE", name="ordertype"), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PAID",
                "COMPLETED",
                "CANCELED",
                "TIMEOUT",
                "REFUNDED",
                name="orderstatus",
            ),
            nullable=True,
        ),
        sa.Column("pay_provider", sa.String(length=50), nullable=True),
        sa.Column("pay_payload", sa.JSON(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("refunded_at", sa.DateTime(), nullable=True),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_order_no"), "orders", ["order_no"], unique=True)
    op.create_index(op.f("ix_orders_plan_id"), "orders", ["plan_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_subscription_id"), "orders", ["subscription_id"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "plan_billing_cycles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "billing_cycle",
            sa.Enum(
                "TRIAL",
                "UNSET",
                "MONTHLY",
                "QUARTERLY",
                "SEMI_ANNUAL",
                "YEARLY",
                "LIFETIME",
                name="billingcycle",
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "billing_cycle", name="uq_plan_billing_cycle"),
    )
    op.create_index(
        op.f("ix_plan_billing_cycles_plan_id"), "plan_billing_cycles", ["plan_id"], unique=False
    )
    op.create_table(
        "plan_server_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("template_emby_user_id", sa.String(length=255), nullable=False),
        sa.Column("template_emby_username", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["emby_servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "server_id", name="uq_plan_server"),
    )
    op.create_index(
        op.f("ix_plan_server_assignments_plan_id"),
        "plan_server_assignments",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_server_assignments_server_id"),
        "plan_server_assignments",
        ["server_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "CANCELED", name="subscriptionstatus"),
            nullable=True,
        ),
        sa.Column(
            "billing_cycle",
            sa.Enum(
                "TRIAL",
                "UNSET",
                "MONTHLY",
                "QUARTERLY",
                "SEMI_ANNUAL",
                "YEARLY",
                "LIFETIME",
                name="billingcycle",
            ),
            nullable=False,
        ),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column(
            "source", sa.Enum("PAYMENT", "CARD", "ADMIN", name="subscriptionsource"), nullable=True
        ),
        sa.Column("vod_times_used", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "system_task_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("task_key", sa.String(length=64), nullable=False),
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=True),
        sa.Column("run_at", sa.DateTime(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["system_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_task_logs_run_at"), "system_task_logs", ["run_at"], unique=False
    )
    op.create_index(
        op.f("ix_system_task_logs_task_id"), "system_task_logs", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_system_task_logs_task_key"), "system_task_logs", ["task_key"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PENDING", "RESOLVED", "CLOSED", name="ticketstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("LOW", "MEDIUM", "HIGH", name="ticketpriority"), nullable=False
        ),
        sa.Column("last_reply_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_priority"), "tickets", ["priority"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)
    op.create_table(
        "vod_favorites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("backdrop_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tmdb_id", "media_type", name="uq_vod_favorites_user_tmdb"),
    )
    op.create_index(
        op.f("ix_vod_favorites_created_at"), "vod_favorites", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_vod_favorites_tmdb_id"), "vod_favorites", ["tmdb_id"], unique=False)
    op.create_index(op.f("ix_vod_favorites_user_id"), "vod_favorites", ["user_id"], unique=False)
    op.create_table(
        "vod_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("quota_consumed", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.String(length=50), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("douban_id", sa.String(length=255), nullable=True),
        sa.Column("moviepilot_subscribe_id", sa.String(length=255), nullable=True),
        sa.Column("moviepilot_download_hash", sa.String(length=255), nullable=True),
        sa.Column("cost_type", sa.String(length=50), nullable=False),
        sa.Column("cost_amount", sa.Integer(), nullable=False),
        sa.Column("fail_reason", sa.String(length=500), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vod_requests_created_at"), "vod_requests", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_vod_requests_status"), "vod_requests", ["status"], unique=False)
    op.create_index(
        op.f("ix_vod_requests_subscription_id"), "vod_requests", ["subscription_id"], unique=False
    )
    op.create_index(op.f("ix_vod_requests_user_id"), "vod_requests", ["user_id"], unique=False)
    op.create_table(
        "payment_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("provider_trade_no", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("raw_callback", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_transactions_order_id"), "payment_transactions", ["order_id"], unique=False
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("sender_user_id", sa.UUID(), nullable=False),
        sa.Column("sender_role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_messages_sender_user_id"),
        "ticket_messages",
        ["sender_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_messages_ticket_id"), table_name="ticket_messages")
    op.drop_index(op.f("ix_ticket_messages_sender_user_id"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_payment_transactions_order_id"), table_name="payment_transactions")
    op.drop_table("payment_transactions")
    op.drop_index(op.f("ix_vod_requests_user_id"), table_name="vod_requests")
    op.drop_index(op.f("ix_vod_requests_subscription_id"), table_name="vod_requests")
    op.drop_index(op.f("ix_vod_requests_status"), table_name="vod_requests")
    op.drop_index(op.f("ix_vod_requests_created_at"), table_name="vod_requests")
    op.drop_table("vod_requests")
    op.drop_index(op.f("ix_vod_favorites_user_id"), table_name="vod_favorites")
    op.drop_index(op.f("ix_vod_favorites_tmdb_id"), table_name="vod_favorites")
    op.drop_index(op.f("ix_vod_favorites_created_at"), table_name="vod_favorites")
    op.drop_table("vod_favorites")
    op.drop_index(op.f("ix_tickets_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_priority"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_system_task_logs_task_key"), table_name="system_task_logs")
    op.drop_index(op.f("ix_system_task_logs_task_id"), table_name="system_task_logs")
    op.drop_index(op.f("ix_system_task_logs_run_at"), table_name="system_task_logs")
    op.drop_table("system_task_logs")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_plan_server_assignments_server_id"), table_name="plan_server_assignments"
    )
    op.drop_index(op.f("ix_plan_server_assignments_plan_id"), table_name="plan_server_assignments")
    op.drop_table("plan_server_assignments")
    op.drop_index(op.f("ix_plan_billing_cycles_plan_id"), table_name="plan_billing_cycles")
    op.drop_table("plan_billing_cycles")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_subscription_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_plan_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_no"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_inviter_user_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_emby_accounts_user_id"), table_name="emby_accounts")
    op.drop_index(op.f("ix_emby_accounts_emby_server_id"), table_name="emby_accounts")
    op.drop_table("emby_accounts")
    op.drop_index(op.f("ix_balance_transactions_user_id"), table_name="balance_transactions")
    op.drop_index(
        op.f("ix_balance_transactions_operator_user_id"), table_name="balance_transactions"
    )
    op.drop_table("balance_transactions")
    op.drop_table("vod_settings")
    op.drop_index(
        "uq_users_username_active",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_users_email_active", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_users_inviter_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_email_verification_token"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tmdb_cache_expires_at"), table_name="tmdb_cache")
    op.drop_index(op.f("ix_tmdb_cache_cache_key"), table_name="tmdb_cache")
    op.drop_table("tmdb_cache")
    op.drop_index(op.f("ix_system_tasks_key"), table_name="system_tasks")
    op.drop_table("system_tasks")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_subscription_groups_name"), table_name="subscription_groups")
    op.drop_index(op.f("ix_subscription_groups_key"), table_name="subscription_groups")
    op.drop_table("subscription_groups")
    op.drop_index(op.f("ix_plans_name"), table_name="plans")
    op.drop_index(op.f("ix_plans_group_name"), table_name="plans")
    op.drop_index(op.f("ix_plans_group_key"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_moviepilot_servers_name"), table_name="moviepilot_servers")
    op.drop_table("moviepilot_servers")
    op.drop_index(op.f("ix_emby_servers_priority"), table_name="emby_servers")
    op.drop_index(op.f("ix_emby_servers_name"), table_name="emby_servers")
    op.drop_table("emby_servers")
    op.drop_index(op.f("ix_docs_title"), table_name="docs")
    op.drop_index(op.f("ix_docs_is_visible"), table_name="docs")
    op.drop_table("docs")
    op.execute("DROP TYPE IF EXISTS ticketstatus")
    op.execute("DROP TYPE IF EXISTS ticketpriority")
    op.execute("DROP TYPE IF EXISTS subscriptionsource")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS ordertype")
    op.execute("DROP TYPE IF EXISTS invitationstatus")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS userstatus")
    op.execute("DROP TYPE IF EXISTS planserverallocationstrategy")
    op.execute("DROP TYPE IF EXISTS planstatus")
    op.execute("DROP TYPE IF EXISTS billingcycle")
    # ### end Alembic commands ###
